# Generated by Django 2.1.1 on 2019-08-13 19:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='phone',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
