# Generated by Django 2.1.1 on 2019-08-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20190813_2357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='phone',
            managers=[
            ],
        ),
    ]
