# Generated by Django 2.1.1 on 2019-08-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190818_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
            preserve_default=False,
        ),
    ]
