# Generated by Django 2.1.1 on 2019-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematik', models.TextField(verbose_name='Тематика')),
                ('is_main', models.BooleanField(verbose_name='основной')),
                ('article', models.ManyToManyField(to='articles.Article')),
            ],
        ),
    ]
