# Generated by Django 2.1.1 on 2019-08-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190817_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='tematik',
        ),
        migrations.AddField(
            model_name='scope',
            name='tematik',
            field=models.CharField(default=1234, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
