# Generated by Django 2.1.3 on 2019-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='width',
            field=models.IntegerField(),
        ),
    ]
