# Generated by Django 2.1.3 on 2019-09-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20190920_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path_csv',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
