# Generated by Django 2.1.1 on 2019-09-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.TextField(default='player'),
            preserve_default=False,
        ),
    ]
